### ISSUE TITLE
don't refresh token if the initial token is invalid

### ISSUE THREAD

**Issue by jovezhong** [timeplus-io/gluon#18]
in the 0.1.1 gluon, for any HTTP request, if the token is invalid, the sdk will try to refresh the token, with at most 24 times.
However if the first token is invalid, I guess we can skip the token refresh, and show the error to the end user that the token is not valid.

The main use case is the user gets an valid token and need to run the script for a long time. We should auto-refresh the token so that the user doesn't need to stop the script and rerun. But if at the beginning the token is invalid, this is considered as misconfig.

**Comment by jovezhong** [comment]
(Jove Github Bot) deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by gangtao** [comment]
plan to switch to api key, token mechanism will be obsolete

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
close this ticket since we moved to api key

**Comment by jovezhong** [comment]
(Jove Github Bot) moved this ticket out of the GitHub project(up to 1200 tickets for one project).
