### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by jhao0117** [timeplus-io/gluon#2]
(gluon) jameshao@JamesdeMacBook-Pro python % python3 -m build
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools>=42)
* Getting dependencies for sdist...
running egg_info
creating src/timeplus.egg-info
writing src/timeplus.egg-info/PKG-INFO
writing dependency_links to src/timeplus.egg-info/dependency_links.txt
writing requirements to src/timeplus.egg-info/requires.txt
writing top-level names to src/timeplus.egg-info/top_level.txt
writing manifest file 'src/timeplus.egg-info/SOURCES.txt'
error: package directory 'src/tests' does not exist

**Comment by jovezhong** [comment]
(Jove Github Bot) moved this ticket out of the GitHub project(up to 1200 tickets for one project).
