### ISSUE TITLE
Generator source doesn't support `range`

### ISSUE THREAD

**Issue by ye11ow** [timeplus-io/gluon#30]
E.g. I'd like to use
```
GeneratorField().name("device").type("string").range(["device_0", "device_1", "device_2"])
```
However, only `limit` is supposed

**Comment by gangtao** [comment]
fixed in `0.1.6`

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) moved this ticket out of the GitHub project(up to 1200 tickets for one project).
