### ISSUE TITLE
cannot insert data with _tp_time

### ISSUE THREAD

**Issue by jovezhong** [timeplus-io/gluon#50]
I created a stream with a single `cnt` column (actually the stream is created automated with Timeplus Sink)

If I use python SDK to insert data, I cannot set the _tp_time column, otherwise it will fail

```python
s = (
    Stream().name("a")
    .column(StreamColumn().name("_tp_time").type("datetime64(3, 'UTC')"))
    .column(StreamColumn().name("cnt").type("uint64"))
)
s.insert([["2022-09-09T09:00:00",9595]])
```

Error
> timeplus.error.TimeplusAPIError: http method post, response code 500, failed to send http post due to {"code":500,"message":"failed to ingest data to stream a: code: 27, message: Code: 27. DB::ParsingException: Cannot parse input: expected '\"' before: '-09-09T09:00:00\",9595]]': (while reading the value of key cnt): \nRow 1:\nColumn 0,   name: cnt, type: uint64, ERROR: text \"[\u003cDOUBLE QUOTE\u003e2022-09-\" is not like uint64\n\n: (at row 1)\n. (CANNOT_PARSE_INPUT_ASSERTION_FAILED) (version 1.0.82)"}

If I remove the _tp_time, then data can be inserted

```python
s = (
    Stream().name("a")
    .column(StreamColumn().name("cnt").type("uint64"))
)
s.insert([[950]])
```

**Comment by jovezhong** [comment]
Enabled the log

`GLUON_LOG_LEVEL=DEBUG python sep15.py `

> 2022-09-15T15:03:58.418494-0700 - DEBUG - post https://latest.timeplus.io:443/api/v1beta1/streams/a/ingest
> 2022-09-15T15:03:58.419142-0700 - DEBUG - insert {'columns': ['cnt'], 'data': [['2022-09-09T09:00:00', 9595]]}
> 2022-09-15T15:03:58.419498-0700 - DEBUG - post https://latest.timeplus.io:443/api/v1beta1/streams/a/ingest with data {"columns": ["cnt"], "data": [["2022-09-09T09:00:00", 9595]]}
> 2022-09-15T15:03:58.524783-0700 - ERROR - http post failed http method post, response code 500, failed to send http post due to {"code":500,"message":"failed to ingest data to stream a: code: 27, message: Code: 27. DB::ParsingException: Cannot parse input: expected '\"' before: '-09-09T09:00:00\",9595]]': (while reading the value of key cnt): \nRow 1:\nColumn 0,   name: cnt, type: uint64, ERROR: text \"[\u003cDOUBLE QUOTE\u003e2022-09-\" is not like uint64\n\n: (at row 1)\n. (CANNOT_PARSE_INPUT_ASSERTION_FAILED) (version 1.0.82)"}

The root cause should be the column array doesn't include the _tp_time

**Comment by jovezhong** [comment]
https://github.com/timeplus-io/gluon/blob/20f5418336bc2afd71ceb9798edee06ac6560fed/python/timeplus/stream.py#L187

**Comment by gangtao** [comment]
By default, gluon will hide the internal header, so when you insert data, the `_tp_time` will not be considerred as these cols are not created by the user. in case you want to override this setting, specify the header should work.  try

```python
s = (
    Stream().name("a")
    .column(StreamColumn().name("_tp_time").type("datetime64(3, 'UTC')"))
    .column(StreamColumn().name("cnt").type("uint64"))
)

headers = ['_tp_time', 'cnt']
s.insert([["2022-09-09T09:00:00",9595]], headers=headers)

```

**Comment by jovezhong** [comment]
oh, I see. I can pass the headers as option parameter

def insert(self, data, headers=None)

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.
