### ISSUE TITLE
Restart the query if the neutron(api server) is restarted

### ISSUE THREAD

**Issue by jovezhong** [timeplus-io/gluon#51]
Today if the neutron gets restarted, the streaming sql will be cancelled.
For the Python SDK client, it'll be great if the query can be resubmitted, or let the client to decide how to resubmit.
Today when the client uses Python SDK to run a streaming query and neutron gets restarted, the query just hangs

**Comment by gangtao** [comment]
1. in case of nuetron restart, the query will complete as normal as the ws is closed 
2. the client side should decide whether to re-submit the query incase of query complete as the SDK does not know what will be the user's choice
