### ISSUE TITLE
view interface

### ISSUE THREAD

**Issue by jhao0117** [timeplus-io/gluon#64]
I'd like to use gluon to create, list, delete and update a view or materialized view

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by gangtao** [comment]
view interface is supported now

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.
