### ISSUE TITLE
DB API and SQLAlchemy support

### ISSUE THREAD

**Issue by gangtao** [timeplus-io/gluon#68]
And when working with other community tools such as LangChain, Querybook, Superset, SQLAlchemy plays as the driver role.
It is better that Timeplus python sdk can support it.

- [pep-0249](https://peps.python.org/pep-0249/)
- https://medium.com/@er.26yashiagarwal/python-database-api-beb8e61109cf
-  https://www.sqlalchemy.org/

**Comment by jovezhong** [comment]
Related ticket https://github.com/timeplus-io/superpartner/issues/34 (private repo)

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.
